version: "3.9"
services:
  api:
    image: 'enrollment.api'
    build:
      context: ./back-end/
      dockerfile: Dockerfile
    container_name: enrollment.api
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: 'enrollment.db'
    build:
      context: ./back-end/postgres/
      dockerfile: Dockerfile
    container_name: enrollment.db
    ports:
      - "5432:5432"

  client:
    image: 'enrollment.client'
    build:
      context: ./front-end/
      dockerfile: Dockerfile
    container_name: enrollment.client
    ports:
      - "4200:4200"