version: "3.9"
services:
  app:
    image: 'enrollment-back-end'
    build:
      context: .
    container_name: enrollment-back-end
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: 'postgres'
    build:
      context: postgres
    container_name: postgres
    ports:
      - "5432:5432"