version: "3.9"
services:
  api:
    image: 'enrollment.api'
    build:
      context: .
    container_name: enrollment.api
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: 'postgres'
    build:
      context: postgres
    container_name: postgres
    ports:
      - "5432:5432"