version: "3.9"
services:
  api:
    image: 'enrollment.api'
    build:
      context: .
    container_name: enrollment.api
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: 'enrollment.db'
    build:
      dockerfile: postgres/Dockerfile
    container_name: enrollment.db
    ports:
      - "5432:5432"